### ISSUE TITLE
Add parameter to control the countdown duration

### ISSUE THREAD

**Issue by dmikushin** [dmikushin/RK3328_Uboot_SPI#1]
Develop a U-boot patch to set the duration of autoboot countdown, for example to 10 seconds:

```
Hit any key to stop autoboot: 0
```

I should be able to do from the U-boot CLI:

```
setenv autoboot_countdown_sec 10
saveenv
```

Upon the next boot, countdown should be 10 seconds.

Do not allow setting countdown less or equal to 0.

If this feature already exists, just explain how to use it.

**Comment by ognjenMarinkovic27** [comment]
There should exist an environment variable bootdelay with this functionality. 

According to the U-Boot reference manual, if the bootdelay is set to 0, the autoboot happens immediately after U-Boot starts. To stop the process and enter the monitor, press a key as soon as the first U-Boot output lines appear. 

Reference:
http://www.learningaboutelectronics.com/Articles/How-to-increase-or-decrease-the-boot-delay-u-boot-before-automatic-boot-process.php

**Comment by dmikushin** [comment]
> There should exist an environment variable bootdelay with this functionality.
> 
> According to the U-Boot reference manual, if the bootdelay is set to 0, the autoboot happens immediately after U-Boot starts. To stop the process and enter the monitor, press a key as soon as the first U-Boot output lines appear.
> 
> Reference: http://www.learningaboutelectronics.com/Articles/How-to-increase-or-decrease-the-boot-delay-u-boot-before-automatic-boot-process.php

Thanks, so by typing `setenv bootdelay 10; saveenv;` we can change the boot delay from within the working U-boot.

But what is the way to hard code the default value of boot delay into the U-boot firmware?

**Comment by ognjenMarinkovic27** [comment]
Lines 453 and  454 of autoboot.c

```C
s = env_get("bootdelay");
bootdelay = s ? (int)simple_strtol(s, NULL, 10) : CONFIG_BOOTDELAY;
```

The default value can be changed with CONFIG_BOOTDELAY

**Comment by dmikushin** [comment]
Excellent, thank you for your solution, @ognjenMarinkovic27 !
