### ISSUE TITLE
Try to run our Uboot firmware in Qemu

### ISSUE THREAD

**Issue by dmikushin** [dmikushin/RK3328_Uboot_SPI#4]
It should be possible to deploy Qemu with a setting for generic ARM Cortex A53 CPU. Please check, if it could boot U-boot.

**Comment by milancimbaljevic** [comment]
This is how i managed to setup u-boot in qemu.
I executed following commands in linux terminal.

```
mkdir qemu-uboot
cd qemu-uboot
git clone https://source.denx.de/u-boot/u-boot.git
cd u-boot
make qemu_arm64_defconfig
make CROSS_COMPILE=aarch64-linux-gnu-
qemu-system-aarch64 -curses -machine virt -cpu cortex-a53 -bios u-boot.bin
```
Then i press Esc + 2 to show u-boot command line.

**Comment by dmikushin** [comment]
Great, thank you for this example! Is it very useful.

**Comment by dmikushin** [comment]
Pushed in 906b4cc4571ea5dca31c58c8e9c63ad746c92e79
