### ISSUE TITLE
Test new wget command of U-boot

### ISSUE THREAD

**Issue by dmikushin** [dmikushin/RK3328_Uboot_SPI#5]
Add building of U-boot with [wget command support](https://www.linaro.org/blog/http-now-supported-in-u-boot/) into the Dockerfile

**Comment by milancimbaljevic** [comment]
#6 Wget support

**Comment by dmikushin** [comment]
Pushed in 5c867a47bd40de11f6b4011f765479ab581fe9a8  , thanks!
